AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Course CI/CD with Jenkins and CircleCI

Parameters:
  Environment:
    Type: String

Resources:
  CircleCiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "circle-ci-service-${Environment}"
      Handler: app.handler
      Runtime: nodejs20.x
      CodeUri: dist/
      Environment:
        Variables:
          Environment: !Ref Environment
      FunctionUrlConfig:
        AuthType: NONE

Outputs:
  CircleCiFunctionEndpoint:
    Description: "CircleCI 2024 Lambda Function URLs"
    Value:
      Fn::GetAtt: CircleCiFunctionUrl.FunctionUrl